# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Precious' do

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '9.0'

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'EZSwiftExtensions', git:'https://github.com/goktugyil/EZSwiftExtensions.git', branch:'swift4'
  pod 'MonkeyKing'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'URLNavigator'
  pod 'JPush'
  pod 'Neat'
  pod 'Starscream'
  pod 'Hue'
  pod 'SwipeBack', '~> 1.1'

end
